BASE:
  - ''
TOOLBOX_MODE: only_test # "train_and_test"  or "only_test"
TEST:
  #METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  METRICS:
    - MAE
    - RMSE
    - MAPE
    - Pearson
    - SNR
  USE_LAST_EPOCH: true
  DATA:
    FILTERING:
      USE_EXCLUSION_LIST: false
      # 未対応機能
      EXCLUSION_LIST:
        - '002'
      SELECT_TASKS: false
      # 未対応(不要)機能
      TASK_LIST:
        - T1
      #TASK_LIST: []
      # annotation記載されている情報なのに手動記載形式なので、将来回収必要
    FS: 30
    DATASET: Olive-VPPG
    DO_PREPROCESS: true # if first time, should be true
    DATA_FORMAT: NDCHW
    #DATA_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/UBFC-PHYS/RawData"          # need to be updated
    #CACHED_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/rppg_toolbox/PreprocessedData"    # Processed dataset save path, need to be updated
    DATA_PATH: /Users/olive_guest/Desktop/rPPG-Toolbox/dataset/Olive-VPPG/dataset
    #CACHED_PATH: "/Users/olive_guest/Desktop/rPPG-Toolbox/PreprocessedData"  
    CACHED_PATH: /Volumes/ELECOM/PreprocessedData
    EXP_DATA_NAME: ''
    BEGIN: 0
    END: 1
    PREPROCESS:
      # 動画データの標準化方法を指定 rawの場合はそのままのデータを使用する
      # モデルとして以下2つの前処理を行ったデータが必要ぽい
      # 詳細は論文読んだ方が良さそう
      DATA_TYPE:
        - DiffNormalized
        - Standardized
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: true
      CHUNK_LENGTH: 30
      CROP_FACE:
        DO_CROP_FACE: true
        BACKEND: RF # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: true
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: true
          # 動画のfpsに合わせてface detectの検出fpsの指定も必要
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: true # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
#DEVICE: cuda:0
DEVICE: cpu
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: DeepPhys
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: FFT # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: false # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10 # In seconds
  MODEL_PATH: final_model_release/PURE_DeepPhys.pth