BASE: ['']
TRAIN_OR_TEST: "only_test" 
TRAIN:
  BATCH_SIZE: 2
  EPOCHS: 10
  LR: 1e-3
  MODEL_FILE_NAME: PURE_UBFC_physnet.pth
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False              # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH:   "/data1/toolbox_data/PURE/RawData"       # need to be updated
    EXP_DATA_NAME: ""
    PREPROCESS :
      DATA_TYPE: ['Raw']
      LABEL_TYPE: Raw
      DO_CHUNK: True
      CLIP_LENGTH: 64
      DYNAMIC_DETECTION: False
      DETECTION_LENGTH: 64
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGER_BOX_SIZE: 1.5
      H: 72
      W: 72
VALID:
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: True                # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/data1/toolbox_data/UBFC/RawData"   # need to be updated
    EXP_DATA_NAME: ""
    PREPROCESS:
      DATA_TYPE: [ 'Raw' ]
      LABEL_TYPE: Raw
      DO_CHUNK: True
      CLIP_LENGTH: 64
      DYNAMIC_DETECTION: False
      DETECTION_LENGTH: 64
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGER_BOX_SIZE: 1.5
      H: 72
      W: 72
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/data1/toolbox_data/UBFC/RawData"     # need to be updated
    EXP_DATA_NAME: ""
    PREPROCESS:
      DATA_TYPE: [ 'Raw' ]
      LABEL_TYPE: Raw
      DO_CHUNK: True
      CLIP_LENGTH: 64
      DYNAMIC_DETECTION: False
      DETECTION_LENGTH: 64
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGER_BOX_SIZE: 1.5
      H: 72
      W: 72
DEVICE: cuda:0
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Physnet
  PHYSNET:
    FRAME_NUM: 64
INFERENCE:
  BATCH_SIZE: 4
  MODEL_PATH: "PreTrainedModels/PURE_SizeW72_SizeH72_ClipLength64_DataTypeRaw_LabelTypeRaw_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len64/PURE_UBFC_physnet.pth_Epoch7.pth"